server:
  port: 8083

spring:
  application:
    name: ms-citas
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: MiSuperClaveParaElExamenT2123456789!@$#
  datasource:
    url: jdbc:mysql://localhost:3306/db_espinoza
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
    baseline-on-migrate: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
